### ISSUE TITLE
$ref issue in el-input

### ISSUE THREAD

**Issue by buremba** [ElemeFE/element#14551]
Element UI version
2.6.0

OS/Browsers version
Chrome / Firefox on Mac OS / Windows 

Vue version
2.6.8

Reproduction Link
I couldn't reproduce the issue in JSFiddle since it's an edge case.

Steps to reproduce
We mount the `el-input` component and remove it after a short period. Even though we do not manually enter the input, somehow the `input` event is triggered and in `this.$nextTick` the input $ref is not found and it throws an exception. 

Observation:
Here is the stacktrace:
<img width="897" alt="screen shot 2019-03-02 at 1 52 20 pm" src="https://user-images.githubusercontent.com/82745/53680976-9bcaf600-3cf3-11e9-8dbb-914f1f396693.png">

What is Expected?
The `handleInput` should be fail-safe and should not throw any exception if the actual input element is not found.

What is actually happening?
It causes the page to throw an exception and crashes the whole application.

**Comment by buremba** [comment]
I'm not able to use the issue-generator. Even if I enter the value of the Vue version, it doesn't accept and suggest any other value: https://cl.ly/586007eb4ed6

**Comment by wacky6** [comment]
Please provide a jsfiddle.

input event derives from browser's input / composition event, I can't see why handleInput was called in this case.

As for the issue generator. Do not remove comments.

**Comment by buremba** [comment]
@wacky6 I'm trying to reproduce the issue on my computer but couldn't be able to do it. On the other hand, according to our issue tracker, 124 users have seen this error so far and it caused the application to crash so I believe that the issue exists but hard to reproduce.

**Comment by wacky6** [comment]
IE users? We know IE has issues regarding input event

**Comment by buremba** [comment]
@wacky6 we do not support IE, it's all Chrome >69 and Firefox

**Comment by wacky6** [comment]
Browser plugin/extensions perhaps

**Comment by buremba** [comment]
@wacky6 I don't think so because I also run into this issue occasionally even though I don't have any extension enabled that modifies the DOM tree.

**Comment by buremba** [comment]
Thanks for looking into the issue @wacky6 . It would be great if you can release a minor (hotfix) version that includes the fix.

**Comment by island205** [comment]
Maybe input is remove  in `this.$nextTick` callback?

**Comment by wacky6** [comment]
@island205 I am working on a pr now. It also fixes regressions in 2.5 release. Now waiting for community to verify the issues are fixed.

**Comment by buremba** [comment]
@wacky6 I will upgrade when you release the new version and will let you know if we see the same error again.

**Comment by buremba** [comment]
@wacky6 the issue still exists on 2.6.1. See:
https://github.com/ElemeFE/element/blob/dev/packages/input/src/input.vue#L306
