### ISSUE TITLE
[Bug Report] Table components cannot be used in tooltip in Electron

### ISSUE THREAD

**Issue by maplewizard** [ElemeFE/element#6721]
### Element UI version
1.4.3

### OS/Browsers version
Deepin/Chrome

### Vue version
2.4.2

### Reproduction Link
[https://jsfiddle.net/LL9py3ny/](https://jsfiddle.net/LL9py3ny/)

### Steps to reproduce
1. 将代码复制为Electron的indel.html；
2. 鼠标停留在Address列；
3. Electron报错

### What is Expected?
期待和jsfiddle行为一致，但是Electron会报错；

### What is actually happening?
 Electron报错：
```
Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.handleCellMouseEnter (/home/cc/workbench/develop/electron-quick-start-master/node_modules/element-ui/lib/element-ui.com…:8894)
    at Proxy.boundFn (/home/cc/workbench/develop/electron-quick-start-master/node_modules/vue/dist/vue.js:187)
    at mouseenter (/home/cc/workbench/develop/electron-quick-start-master/node_modules/element-ui/lib/element-ui.com…:8733)
    at HTMLTableCellElement.invoker (/home/cc/workbench/develop/electron-quick-start-master/node_modules/vue/dist/vue.js:1820)
```

===========
element-ui.com…:8894行：

    tooltip.$refs.popper.style.display = 'none';

并不存在style这个属性

**Comment by Leopoldthecoder** [comment]
Fixed in #6722

**Comment by maplewizard** [comment]
@Leopoldthecoder I have followed the modification and the errors vanished, but the tooltip still cannot come out. Is there any difference between Electron and normal browser?  Why it still not come out?

**Comment by Leopoldthecoder** [comment]
Actually I don't know much about Electron. If it works fine in browsers, I guess it's not a bug on Element's side. Sorry I can't help you here.
