### ISSUE TITLE
[Bug Report] default-value option for daterange and datetimerange pickers

### ISSUE THREAD

**Issue by syn-zeta** [ElemeFE/element#7101]
### Element UI version
1.4.4

### OS/Browsers version
OS X 10.11 / Chrome 60

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/r8v1sp8g/](https://jsfiddle.net/r8v1sp8g/)

### Steps to reproduce
- Create a `daterange` type picker
- Set its `default-value` attribute to an array containing two `Date` objects (since this is the same representation as the `v-model` value that the component sets)
- Click on the component's input field to expand the picker
- Notice that no date range is selected

### What is Expected?
[DatePicker's documentation](http://element.eleme.io/#/en-US/component/date-picker#attributes) lists the `default-value` attribute to set the initial value of the picker, but this only works for the `date` and `datetime` types and not `daterange` or `datetimerange` type pickers.

### What is actually happening?
The `default-value` attribute is ignored for `daterange` or `datetimerange` type pickers.

For range type pickers, the default value is ignored [here](https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/panel/date-range.vue#L233-L234), as opposed to it being used for date/datetime pickers [here](https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/panel/date.vue#L363).

[Multiple previous issues for this exist](https://github.com/ElemeFe/element/issues?utf8=%E2%9C%93&q=is%3Aissue%20daterange%20default), but they were all closed without a proper resolution.

**Comment by Leopoldthecoder** [comment]
Fixed in #7073

**Comment by syn-zeta** [comment]
@Leopoldthecoder @wacky6
That doesn't seem to fix it. The issue is more apparent in the `datetimerange` picker where all the fields are still blank vs `datetime` picker where the fields in the panel are filled with the default value provided: https://jsfiddle.net/u2opvyxa/2/

**Comment by wacky6** [comment]
So what do you expect for datetimerange?

default-value is for setting month/year when panel opens for daterange.

**Comment by syn-zeta** [comment]
Yeah, but the fields should be filled in to keep the behavior consistent across the panels. So, the default value for range pickers need two values to work properly -- either an array of two Date objects or two date strings.

**Comment by wacky6** [comment]
If you need to fill the panel, just bind the value.

**Comment by syn-zeta** [comment]
Then it will not be the same behavior as of just `date` or `datetime` type pickers.

**Comment by Leopoldthecoder** [comment]
The intention of `default-value` is just for configuring which year / month you want the end user to see when he opens the date panel. So for the `date` type, `default-value` shouldn't highlight the set date (it only highlights the date but the bound value is not updated: https://jsfiddle.net/hqq8ptha/1/). I'll correct this.

**Comment by syn-zeta** [comment]
My bad, I actually meant the [`datetime` type picker where the fields in the panel are pre-filled with the `default-value` provided, and the user can just click "ok" to update the bound value](https://jsfiddle.net/u2opvyxa/2/). This is a good ability which is not made possible in PR#7073 with daterange/datetimerange pickers.

**Comment by wacky6** [comment]
Seems to be a bug in `datetime`, it will fill the input fields regardless of `default-value`.

**Comment by syn-zeta** [comment]
@wacky6 It is intentional:

https://github.com/ElemeFE/element/blob/dev/packages/date-picker/src/panel/date.vue#L363

**Comment by Leopoldthecoder** [comment]
@syn-zeta I know you want `default-value` to pre-fill the date range, but that's not `default-value` is meant for (admittedly the name `default-value` is quite confusing, should we change it to `default-view` or something?).

`default-value` is designed for a scenario where the end user has to select a date or date range far in the future / past, say 1990s. Setting `default-value` to `1990, 0, 1` saves the user's pain of having to click the previous button dozen times.

For `date` and `datetime`, `default-value` has a side effect of highlighting the date / filling the input field (but it does not change the binding value). I'm not sure if this side effect can be removed.

**Comment by syn-zeta** [comment]
https://github.com/ElemeFE/element/issues/4143 is where that behavior was implemented. I cannot really understand the discussion there, but if the intention behind it is different than what I'm thinking, then perhaps converting this issue to a feature request for settings default values will be acceptable?

**Comment by Leopoldthecoder** [comment]
Setting default values can be done by binding the value: https://jsfiddle.net/u2opvyxa/3/

**Comment by syn-zeta** [comment]
Binding a value is a step further than simply suggesting a value to the user. Setting the default value (pre-filling the fields) allows the user to confirm, and then the rest of the application can update accordingly.

Use case: A data table column filtered by a datetimerange component. Binding the value will apply the filter, but pre-filling the fields will allow the user to open the filter and simply click OK (with the most common need already filled in), instead of them spending time going back and forth in the calendar to select the commonly used range.

**Comment by syn-zeta** [comment]
I realize this is a good use of the shortcuts, but sometimes the design may not allow it. In any case, I have a workaround, so this issue can remain closed. https://jsfiddle.net/j51cok0m/

**Comment by wacky6** [comment]
Actually, when I first implemented default-value, it was intended to be used with `date` panel only. 

Expanding to other panels is great, but we need to elaborate on intended behaviors.
