### ISSUE TITLE
[Bug Report] datetime with format "yyyy-MM-dd HH" work odd

### ISSUE THREAD

**Issue by lerit** [ElemeFE/element#7147]
### Element UI version
1.4.4

### OS/Browsers version
win 10

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/mLxLmzua/2/](https://jsfiddle.net/mLxLmzua/2/)

### Steps to reproduce
open the jsfiddle link,you can see three datetime component with odd response

### What is Expected?
work fine with format 'yyyy-MM-dd HH'

### What is actually happening?
with different value,first datetime throw error in console;second and third component work well partial,but the hour display in the date area

**Comment by lerit** [comment]
![01](https://user-images.githubusercontent.com/4743467/30684511-0c837732-9ee4-11e7-8906-ccbcc7445a4e.png)

**Comment by Leopoldthecoder** [comment]
Fixed in #7185

**Comment by lerit** [comment]
still throw error after update to 1.4.5
you can click the first datepicker,and see the console
https://jsfiddle.net/mLxLmzua/3/

**Comment by lerit** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
value should be a Date object: https://jsfiddle.net/mLxLmzua/5/
